version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eatrack
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - minha_rede

  app:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "6868:8080"
    volumes:
      - .m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/eatrack?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_DDL_AUTO=update
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge

volumes:
  db:
