spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/eatrack?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
    time-zone: Brazil/East

secret:
  jwt:
    SECRET_KEY: ${JWT_SECRET:EAT##TRACK}
